id is:3knxnga3
Launching wandb...
Launching tensorboard...
Logging txt...
/home/tho/anaconda3/envs/scrimp/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py:115: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
[36m(pid=32984)[39m /home/tho/anaconda3/envs/scrimp/lib/python3.7/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
[36m(pid=32984)[39m   warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
[36m(pid=32978)[39m /home/tho/anaconda3/envs/scrimp/lib/python3.7/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
[36m(pid=32978)[39m   warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
[36m(pid=32986)[39m /home/tho/anaconda3/envs/scrimp/lib/python3.7/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
[36m(pid=32986)[39m   warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
[36m(pid=32980)[39m /home/tho/anaconda3/envs/scrimp/lib/python3.7/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
[36m(pid=32980)[39m   warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
[36m(pid=32985)[39m /home/tho/anaconda3/envs/scrimp/lib/python3.7/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
[36m(pid=32985)[39m   warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
[36m(pid=32977)[39m /home/tho/anaconda3/envs/scrimp/lib/python3.7/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
[36m(pid=32977)[39m   warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
[36m(pid=32979)[39m /home/tho/anaconda3/envs/scrimp/lib/python3.7/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
[36m(pid=32979)[39m   warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
[36m(pid=32987)[39m /home/tho/anaconda3/envs/scrimp/lib/python3.7/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
[36m(pid=32987)[39m   warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
[36m[1m(scheduler +34s)[39m[22m Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
[33m[1m(scheduler +34s)[39m[22m Warning: The following resource request cannot be scheduled right now: {'GPU': 0.0588, 'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
2024-03-07 02:01:26,047	WARNING worker.py:1228 -- The actor or task with ID fffffffffffffffff9effc474ddc2c85b069f35301000000 cannot be scheduled right now. You can ignore this message if this Ray cluster is expected to auto-scale or if you specified a runtime_env for this actor or task, which may take time to install.  Otherwise, this is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increasing the resources available to this Ray cluster.
Required resources for this actor or task: {GPU: 0.058800}, {CPU: 1.000000}
Available resources on this node: {0.000000/8.000000 CPU, 355121880.029297 GiB/355121880.029297 GiB memory, 0.529600/1.000000 GPU, 177560939.990234 GiB/177560939.990234 GiB object_store_memory, 1.000000/1.000000 node:172.21.164.149}
In total there are 0 pending tasks and 8 pending actors on this node.
Traceback (most recent call last):
  File "driver.py", line 388, in <module>
    main()
  File "driver.py", line 294, in main
    "reward": eval_performance_dict['per_r']}
UnboundLocalError: local variable 'eval_performance_dict' referenced before assignment
Traceback (most recent call last):
  File "driver.py", line 388, in <module>
    main()
  File "driver.py", line 294, in main
    "reward": eval_performance_dict['per_r']}
UnboundLocalError: local variable 'eval_performance_dict' referenced before assignment
CTRL-C pressed. killing remote workers
Saving Final Model !